# Generated by Django 3.2.13 on 2022-09-14 18:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('allmias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamography',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=None, size=(224, 224), upload_to='mammography/'),
        ),
    ]
