# Generated by Django 3.2.13 on 2022-09-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmias', '0002_alter_mamography_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mamography',
            name='presicion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
