# Generated by Django 3.2.13 on 2022-09-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allmias', '0003_mamography_presicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamography',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
